### PR TITLE
Upgrade to ASM 5.0.3

### PR DESCRIPTION
**Pull request by HiJon89**
For full Java 8 compatibility

### CODE REVIEW

**Comment by NathanSweet** [comment]
Is this going to cause problems with people that use an older ASM version?
This has happened many times before and is why I believe we provide shaded
JARs. The shaded JARs will continue to be generated correctly and work fine
for people with an old ASM?

**Comment by HiJon89** [comment]
The shaded JAR is still being generated as before, is there any reason to not just always bundle and relocate ASM? This is what Guice does for example. The overhead is negligible (asm 5.0.3 is just 25 classes) and it avoids considerable headaches for people using the library

**Comment by NathanSweet** [comment]
It is not nice to always shade all dependencies. If someone wants ASM shaded, they should get the shaded JAR.

**Comment by HiJon89** [comment]
One issue is that the shaded JAR still uses the normal POM so you still end up with a dep on ASM that needs to be excluded. The other issue is that using a classifier changes the maven coordinates so it doesn't play nice with dependencyManagement (ie, I can't force all my dependencies to use the shaded JAR). The separate coordinates also opens up the possibility of getting both the normal and shaded JARs on the classpath at the same time which isn't desirable and if they're different versions it can cause very hard to track down bugs. If you want to go the route of having a separate shaded JAR I think the way to go about it is to have it build the same maven coordinates with shaded appended to the version (ie, 1.10.1-shaded)

**Comment by NathanSweet** [comment]
I don't think libraries should shade dependencies by default in general, but definitely not to workaround any possible deficiencies with Maven. If our Maven setup can be improved, we should focus on that. I don't personally manage the Maven stuff. @magro or @romix can likely chime in.

If the shaded JAR stuff will work with this PR, I'm all for merging.

**Comment by hepin1989** [comment]
how about this now?
how about provide classifier one if that matters or like this 
HikariCP-java6 & HikariCP.

**Comment by magro** [comment]
Upgrading asm should be fine. 

@HiJon89 can you open another issue for the  shaded jar uses regular pom case?

**Comment by magro** [comment]
I just pushed this with reflectasm-1.10.1 to maven central.

**Pull request merged**
